---
sudo: true
services: docker

env:
  - distro: centos7

before_install:
  - sudo yum install -y make

script:
  - container_id=$(mktemp)
  # Download test shim.
  #- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - wget -O ${PWD}/Makefile https://raw.githubusercontent.com/mauromedda/ansible-centos7-ci/master/tests/Makefile
  - cd ${PWD}

  # Run tests.
  - make

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
